import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Keypair,PublicKey} from '@solana/web3.js';
import {Buffer} from 'buffer';
import {connection,PROGRAM,RPC,decode,actionIx,initializeIx,send,Booking} from './chain';
import './style.css';
globalThis.Buffer=Buffer;
const names=['Alex','Sam','Jordan'];
const short=(s:string)=>`${s.slice(0,6)}…${s.slice(-5)}`;
function App(){
 const [view,setView]=useState<'group'|'hotel'>('group');const [role,setRole]=useState(0);
 const [keys,setKeys]=useState<(Keypair|null)[]>([null,null,null,null]);const [address,setAddress]=useState(localStorage.getItem('crewfund-escrow')||'');
 const [state,setState]=useState<Booking|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [receipt,setReceipt]=useState('');const [now,setNow]=useState(Date.now()/1000);const [balance,setBalance]=useState(0);const [chainTime,setChainTime]=useState(0);
 const local=RPC.includes('localhost')||RPC.includes('127.0.0.1');const safe=local||RPC.includes('devnet');
 const actor=keys[view==='hotel'?3:role];
 async function refresh(){
  if(actor)setBalance(await connection.getBalance(actor.publicKey));
  if(!address||!PROGRAM)return;
  const a=await connection.getAccountInfo(new PublicKey(address));if(!a||!a.owner.equals(new PublicKey(PROGRAM)))throw Error('Escrow not found for this program.');
  setState(decode(a.data));const slot=await connection.getSlot();setChainTime((await connection.getBlockTime(slot))||0);if(actor)setBalance(await connection.getBalance(actor.publicKey));
 }
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()/1000),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));const t=setInterval(()=>refresh().catch(e=>setError(e.message)),3000);return()=>clearInterval(t)},[address,actor]);
 async function run(fn:()=>Promise<string>){setBusy(true);setError('');try{const signature=await fn();setReceipt(signature);await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function importKey(file:File,index:number){try{const a=JSON.parse(await file.text());const k=Keypair.fromSecretKey(Uint8Array.from(a));setKeys(old=>old.map((v,i)=>i===index?k:v));setError('')}catch{setError('Please choose a Solana test keypair JSON file.')}}
 async function create(){if(!keys.every(Boolean))throw Error('Import all four test wallets first.');const slot=await connection.getSlot();const time=(await connection.getBlockTime(slot))!;const {escrow,ix}=initializeIx(new PublicKey(PROGRAM),keys[0]!.publicKey,keys[3]!.publicKey,keys.slice(0,3).map(k=>k!.publicKey),time+600,BigInt(Date.now()));const s=await send(connection,keys[0]!,ix);setAddress(escrow.toBase58());localStorage.setItem('crewfund-escrow',escrow.toBase58());return s;}
 const deposited=state?[0,1,2].filter(i=>state.deposits&(1<<i)).length:0;
 const expired=!!state&&chainTime>=state.deadline;const done=state?.paid;const correctActor=!!actor&&!!state&&actor.publicKey.equals(view==='hotel'?state.hotel:state.participants[role]);
 const seconds=state?Math.max(0,Math.floor(state.deadline-now)):0;
 const act=(op:1|2|3)=>run(()=>{if(!safe)throw Error('Only Localnet and Devnet are allowed.');if(!actor)throw Error('Import your test wallet first.');return send(connection,actor,actionIx(new PublicKey(PROGRAM),actor.publicKey,new PublicKey(address),op))});
 return <div className="shell"><header><a className="brand" href="#"><span className="logo">C</span>CrewFund<span className="beta">DEMO</span></a><nav><button className={view==='group'?'selected':''} onClick={()=>setView('group')}>Your group</button><button className={view==='hotel'?'selected':''} onClick={()=>setView('hotel')}>Hotel portal</button></nav><span className="network"><i/>{local?'Local validator':'Devnet'} · Test SOL</span></header>
 <main><div className="eyebrow">SHARED PLANS. INDIVIDUAL CONTROL.</div><h1>{view==='group'?'A stay worth sharing.':'Confirm their next chapter.'}</h1><p className="intro">{view==='group'?'Three friends. One booking. Funds protected until the hotel confirms.':'Only the fixed hotel wallet can confirm a fully funded booking.'}</p>
 <div className="layout"><section><article className="hotel"><div className="illustration"><div className="sun"/><div className="building"><span/><span/><span/><span/><span/><span/></div><div className="ground"/><div className="image-caption">A LITTLE ROOM FOR BIG IDEAS</div></div><div className="hotel-body"><span className="tag">FICTIONAL TEST HOTEL</span><h2>Harbor House</h2><p>Hackathon weekend · 1 room · 3 students</p><div className="offer"><div><small>Fixed group total</small><strong>0.03 <em>Test SOL</em></strong></div><div><small>Each participant</small><strong>0.01 <em>Test SOL</em></strong></div></div><p className="fine">No real reservation. No euro payment. Localnet / Devnet funds only.</p></div></article>
 <article className="rules"><h3>Trust the rules, enjoy the trip.</h3><div><b>01</b><p><strong>Everyone funds their own share</strong><span>Three fixed wallets, one deposit each.</span></p></div><div><b>02</b><p><strong>The hotel confirms</strong><span>Only the fixed provider receives the full payment.</span></p></div><div><b>03</b><p><strong>No booking? Get your share back.</strong><span>After the deadline, each depositor claims their own refund.</span></p></div></article></section>
 <aside><article className="funding"><div className="card-top"><h3>{view==='group'?'Your shared booking':'Provider confirmation'}</h3><span className="tag">{!state?'NOT CREATED':done?'CONFIRMED':expired?'EXPIRED':'FUNDING'}</span></div><div className="amount">{(deposited*0.01).toFixed(2)}<span> / 0.03 Test SOL deposited</span></div><div className="progress"><div style={{width:`${deposited/3*100}%`}}/></div><p className="progress-copy">{deposited} of 3 participants funded</p><div className="members">{names.map((name,i)=><div key={name}><span className={'avatar avatar'+i}>{name[0]}</span><div><strong>{name}</strong><small>{state?short(state.participants[i].toBase58()):'Wallet not set'}</small></div><span className="member-status">{state?.refunds&&(state.refunds&(1<<i))?'Refunded':state?.deposits&&(state.deposits&(1<<i))?'✓ Funded':'Pending'}</span></div>)}</div><div className="deadline"><span>Funding deadline</span><strong>{state?new Date(state.deadline*1000).toLocaleTimeString('en-GB'):'Not set'}</strong><small>{done?'Hotel confirmed':expired?'Refunds are available':state?`${Math.floor(seconds/60)}m ${seconds%60}s remaining`:'Create a booking to start'}</small></div>
 {view==='group'?<><label className="label">Acting as<select value={role} onChange={e=>setRole(Number(e.target.value))}>{names.map((n,i)=><option key={n} value={i}>{n}</option>)}</select></label><button className="primary" disabled={busy||!correctActor||done||expired||!!(state!.deposits&(1<<role))} onClick={()=>act(1)}>{busy?'Confirming transaction…':'Deposit 0.01 Test SOL'}</button><button className="secondary" disabled={busy||!correctActor||done||!expired||!(state!.deposits&(1<<role))||!!(state!.refunds&(1<<role))} onClick={()=>act(3)}>Claim my refund</button></>:<button className="primary" disabled={busy||!correctActor||done||expired||deposited!==3} onClick={()=>act(2)}>Confirm booking & receive 0.03 Test SOL</button>}
 <p className="fine">{actor?`Test wallet: ${short(actor.publicKey.toBase58())} · ${(balance/1e9).toFixed(4)} Test SOL`:'Import the corresponding test wallet below.'}</p>{error&&<div className="error" role="alert">{error}</div>}{receipt&&<div className="receipt"><strong>Transaction confirmed · {local?'Local validator':'Devnet'}</strong>{local?<code>{receipt}</code>:<a href={`https://explorer.solana.com/tx/${receipt}?cluster=devnet`} target="_blank" rel="noreferrer">View Solana Explorer ↗</a>}</div>}
 </article><p className="escrow-note">◈ Program-controlled escrow<br/><span>Group members cannot withdraw pooled funds.</span></p></aside></div>
 <details className="setup" open><summary>Demo setup & blockchain details</summary><p>Import four separate, disposable test keypair JSON files. Keys stay in this page’s memory and are cleared on reload. Never import a wallet holding real funds.</p><div className="wallets">{[...names,'Hotel'].map((name,i)=><label key={name}>{name}<input type="file" accept=".json" onChange={e=>{if(e.target.files?.[0])importKey(e.target.files[0],i)}}/><span>{keys[i]?short(keys[i]!.publicKey.toBase58()):'Not imported'}</span></label>)}</div><div className="setup-actions"><button className="secondary" disabled={busy||!PROGRAM||!safe||!keys.every(Boolean)} onClick={()=>run(create)}>Create 10-minute booking</button><button className="secondary" disabled={!actor||busy||!safe} onClick={()=>run(async()=>{const s=await connection.requestAirdrop(actor!.publicKey,100_000_000);const b=await connection.getLatestBlockhash();const r=await connection.confirmTransaction({...b,signature:s},'confirmed');if(r.value.err)throw Error('Airdrop failed');return s})}>Get 0.1 Test SOL</button></div><label className="label">Open existing escrow<input value={address} onChange={e=>{setError('');setState(null);setAddress(e.target.value);localStorage.setItem('crewfund-escrow',e.target.value)}} placeholder="Escrow public address"/></label><p className="fine">RPC: {RPC}<br/>Program: {PROGRAM||'Not deployed / configured'}<br/>Escrow: {address||'Not created'}<br/>Status comes from RPC account data. No simulated payment mode.</p></details>
 </main><footer>CrewFund · A Solana hackathon prototype <span>Test funds. Real escrow rules.</span></footer></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
